asset_market/models.py
# -*- coding: utf-8 -*-
# <standard imports>
from __future__ import division
from otree.db import models
from otree.constants import BaseConstants
from otree.models import BaseSubsession, BaseGroup, BasePlayer
from otree import widgets
from otree.common import Currency as c, currency_range
import random
# </standard imports>
from random import randint


author = 'Dev'

doc = """

In this asset market, two players trade shares that give probabilistic dividends. It is based on
<a href="http://www.tandfonline.com/doi/abs/10.3200/JECE.40.1.027-037">
    Bostian and Holt (2010).
</a>

"""

source_code = "https://github.com/oTree-org/oTree/tree/master/asset_market"


bibliography = (
    (
        'Smith, Vernon L., Gerry L. Suchanek, and Arlington W. Williams. '
        '"Bubbles, crashes, and endogenous expectations in experimental spot '
        'asset markets."Econometrica: Journal of the Econometric Society '
        '(1988): 1119-1151.'
    ),
    (
        'Smith, Alec, et al. "Irrational exuberance and neural crash warning '
        'signals during endogenous experimental market bubbles." Proceedings '
        'of the National Academy of Sciences 111.29 (2014): 10503-10508.'
    ),
    (
        'Palan, Stefan. "A review of bubbles and crashes in experimental '
        'asset markets." Journal of Economic Surveys 27.3 (2013): 570-588.'
    )
)


links = {
    "Wikipedia": {
        "Stock Market Bubbles":
            "https://en.wikipedia.org/wiki/Stock_market_bubble",
        "Market Games":
            "https://en.wikipedia.org/wiki/Experimental_economics#Market_games"
    }
}


keywords = ("Stock Market", "Finance", "Bubble", "Trade")


class Constants(BaseConstants):
    name_in_url = 'asset_market'
    players_per_group = 2
    num_rounds = 2

    understanding_1_correct = 'P=2.5, N=2'
    understanding_2_correct = '$8, $12'
    endowment = c(20)
    num_shares = 10


class Subsession(BaseSubsession):

    def before_session_starts(self):
        if self.round_number == 1:
            for p in self.get_players():
                p.cash = Constants.endowment


class Group(BaseGroup):
    # transaction fields
    transaction_price = models.CurrencyField(doc="""Given by 0.5*(BP+SP)""")
    shares_traded = models.PositiveIntegerField(initial=0)

    # dividend fields
    dividend_per_share = models.CurrencyField()
    is_dividend = models.BooleanField(initial=False, doc="""Indicates whether dividend is issued""")

    # method to set cash and shares to balance in previous round
    def set_assets_to_previous(self):
        for p in self.get_players():
            p.cash = p.in_previous_rounds()[-1].cash
            p.shares = p.in_previous_rounds()[-1].shares

    def trade(self):
        buyers = [p for p in self.get_players() if p.order_type == 'Buy']
        sellers = [p for p in self.get_players() if p.order_type == 'Sell']
        # both lists must have exactly 1 element
        if not (buyers and sellers):
            return
        buyer = buyers[0]
        seller = sellers[0]
        if seller.sp >= buyer.bp or (buyer.bn * buyer.bp == 0) or (seller.sn * seller.sp == 0):
            return

        # average of buy & sell price
        self.transaction_price = 0.5*(buyer.bp+seller.sp)
        self.shares_traded = min(buyer.bn, seller.sn)

        # adjust shares and cash
        amount = self.transaction_price * self.shares_traded
        if amount > buyer.cash:
            return

        buyer.shares += self.shares_traded
        buyer.cash -= amount

        seller.shares -= self.shares_traded
        seller.cash += amount

    def set_dividend(self):
        self.dividend_per_share = randint(1,2)
        self.is_dividend = True

        # adjust cash
        for p in self.get_players():
            p.cash += (
                p.shares * self.dividend_per_share
                if p.shares != 0 else
                p.cash
            )


class Player(BasePlayer):
    # <built-in>
    subsession = models.ForeignKey(Subsession)
    group = models.ForeignKey(Group, null = True)
    # </built-in>

    # initial shares and payoff
    shares = models.PositiveIntegerField(initial=5)

    cash = models.CurrencyField()

    # default allocated shares for both players; provides a range for buyers; sellers' range is limited by the number of shares they have


    # order fields
    bp = models.CurrencyField(initial=0.00, doc="""maximum buying price per share""")
    bn = models.PositiveIntegerField(initial=0,
                                     choices=range(0, Constants.num_shares+1, 1),
                                     doc="""number of shares willing to buy""")
    sp = models.CurrencyField(initial=0.00, doc="""minimum selling price per share""")
    sn = models.PositiveIntegerField(initial=0, doc="""number of shares willing to sell.""")

    order_type = models.CharField(choices=['Sell', 'Buy', 'None'],
                                  doc="""player: buy or sell?""",
                                  widget=widgets.RadioSelectHorizontal)

    def other_player(self):
        """Returns other player in group. Only valid for 2-player groups."""
        return self.get_others_in_group()[0]

    QUESTION_1_CHOICES = ['P=3, N=2','P=2, N=3','P=2.5, N=3','P=2.5, N=2','No transaction will take place',]
    QUESTION_2_CHOICES = ['$8, $12', '$12, $8', '$8, $8', '$12, $12', '$10, $10']

    understanding_question_1 = models.CharField(choices=QUESTION_1_CHOICES, widget=widgets.RadioSelect())
    understanding_question_2 = models.CharField(choices=QUESTION_2_CHOICES, widget=widgets.RadioSelect())

    # check correct answers
    def is_understanding_question_1_correct(self):
        return self.understanding_question_1 == Constants.understanding_1_correct

    def is_understanding_question_2_correct(self):
        return self.understanding_question_2 == Constants.understanding_2_correct


    def set_payoff(self):
        self.payoff = 0
        if self.subsession.round_number == Constants.num_rounds:
            self.payoff = self.cash
        else:
            self.payoff = 0

asset_market/_builtin/__init__.py
# This file is auto-generated. Don't change anything in this file.
from .. import models
import otree.views
import otree.test

class Page(otree.views.Page):
    z_models = models

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()


class WaitPage(otree.views.WaitPage):

    z_models = models

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()


class Bot(otree.test.Bot):

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()



asset_market/views.py
# -*- coding: utf-8 -*-
from __future__ import division
from . import models
from ._builtin import Page, WaitPage
from otree.common import Currency as c, currency_range
from .models import Constants
from otree.common import safe_json


def vars_for_all_templates(self):
    return {
        'total_q': 2,
        'round_num': self.subsession.round_number,
        'num_of_rounds': Constants.num_rounds,  # no of periods
        'num_participants': Constants.players_per_group,
    }


class Introduction(Page):

    def is_displayed(self):
        return self.subsession.round_number == 1


class Instructions(Page):

    def is_displayed(self):
        return self.subsession.round_number == 1


class Question1(Page):

    form_model = models.Player
    form_fields = ['understanding_question_1']

    template_name = 'asset_market/Question.html'

    def is_displayed(self):
        return self.subsession.round_number == 1

    def vars_for_template(self):
        return {
            'num_q': 1,
        }


class Feedback1(Page):

    def is_displayed(self):
        return self.subsession.round_number == 1

    template_name = 'asset_market/Feedback.html'

    def vars_for_template(self):
        return {
            'num_q': 1,
            'answer': self.player.understanding_question_1,
            'correct': Constants.understanding_1_correct,
            'is_correct': self.player.is_understanding_question_1_correct(),
        }


class Question2(Page):

    form_model = models.Player
    form_fields = ['understanding_question_2']

    def is_displayed(self):
        return self.subsession.round_number == 1

    template_name = 'asset_market/Question.html'

    def vars_for_template(self):
        return {
            'num_q': 2,
        }


class Feedback2(Page):

    def is_displayed(self):
        return self.subsession.round_number == 1

    template_name = 'asset_market/Feedback.html'



    def vars_for_template(self):
        return {
            'num_q': 2,
            'answer': self.player.understanding_question_2,
            'correct': Constants.understanding_2_correct,
            'is_correct': self.player.is_understanding_question_2_correct(),
        }


class OrderWaitPage(WaitPage):

    def after_all_players_arrive(self):
        if self.subsession.round_number > 1:
            self.group.set_assets_to_previous()


class Order(Page):

    form_model = models.Player
    form_fields = ['order_type', 'bp', 'bn', 'sn', 'sp']

    def sn_choices(self):
        return range(0, self.player.shares + 1, 1)

    def bp_choices(self):
        return currency_range(0, self.player.cash, 0.5)

    def sp_choices(self):
        return currency_range(0, self.player.cash, 0.5)



class TransactionWaitPage(WaitPage):

    def after_all_players_arrive(self):
        self.group.trade()


class Transaction(Page):

    def is_displayed(self):
        return True

    def vars_for_template(self):
        return {
            'transaction_price': self.group.transaction_price or 0
        }

class DividendWaitPage(WaitPage):

    def after_all_players_arrive(self):
        self.group.set_dividend()


class Dividend(Page):

    def is_displayed(self):
        return True

    def vars_for_template(self):
        return {
            'dividend_gain': self.group.dividend_per_share * self.player.shares if self.player.shares != 0 else 0
        }


class ResultsWaitPage(WaitPage):

    def after_all_players_arrive(self):
        for p in self.group.get_players():
            p.set_payoff()


class Results(Page):

    def is_displayed(self):
        return self.subsession.round_number == Constants.num_rounds

    def total_payoff(self):
        return self.player.payoff + self.player.participant.session.participation_fee

    def vars_for_template(self):

        # create chart lists
        transaction_price_list = []
        dividend_per_share_list = []
        shares_traded_list = []

        for p in self.player.in_all_rounds():
            transaction_price_list.append(int(p.group.transaction_price or 0))
            dividend_per_share_list.append(int(p.group.dividend_per_share))
            shares_traded_list.append(p.group.shares_traded)

        return {

            'transaction_price_list': safe_json(transaction_price_list),
            'dividend_per_share_list': safe_json(dividend_per_share_list),
            'shares_traded_list': safe_json(shares_traded_list),
        }


page_sequence=[
         Introduction,
         Instructions,
         Question1,
         Feedback1,
         Question2,
         Feedback2,
        OrderWaitPage,
        Order,
        TransactionWaitPage,
        Transaction,
        DividendWaitPage,
        Dividend,
        ResultsWaitPage,
        Results,
    ]

asset_market/templates/asset_market/Dividend.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Dividend Distribution (Period {{ round_num }} of {{ num_of_rounds }})
{% endblock %}

{% block content %}



    <p>
        The dividend per share for Period {{ round_num }} is {{ group.dividend_per_share }}. You have {{ player.shares }} shares thus receive {{ dividend_gain }}
        for dividends in total. Now your positions are the following:
    </p>

    <h5 class="text-info text-center">Cash: {{ player.cash }};  Shares: {{ player.shares }}</h5>

    {% next_button %}

    {% include 'asset_market/Rules.html' %}


{% endblock %}

asset_market/templates/asset_market/Instructions.html
{% extends "global/Base.html" %}{% load staticfiles otree_tags %}{% block title %}    Instructions{% endblock %}{% block content %}    <p>        In this asset market, there are {{ num_participants }} participants. Both of you are endowed with {{ cash }} cash and        {{ shares }} shares of stock.        Shares pay random dividends at the end of each period. There are {{ num_of_rounds }} periods during which you are free to submit buy/sell orders to        trade shares. At the end of the study, your cash positions count for your payoffs; your shares are redeemed for free.     </p>    <p>        Both of you see the same instruction. The identical instruction will be displayed on every page for your convenience.    </p>    {% next_button %}    {% include 'asset_market/Rules.html' %}{% endblock %}

asset_market/templates/asset_market/Introduction.html
{% extends "global/Base.html" %}{% load staticfiles otree_tags %}{% block title %}    Introduction{% endblock %}{% block content %}    <p>        In this asset market, two participants are endowed with cash and stock shares that distribute random dividends. In each period,        participants could submit buy /sell orders that will determine a transaction price. At the end of each period, dividends are        distributed to participants according to their numbers of shares. Shares are not redeemed at the end of the study. Traders’        cash positions completely determine their payoffs from the asset market. The study is adapted from        <a href="http://www.tandfonline.com/doi/abs/10.3200/JECE.40.1.027-037">Bostian&Holt (2010).</a>     </p>    {% next_button %}{% endblock %}

asset_market/templates/asset_market/Order.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Submit Order (Period {{ round_num }} of {{ num_of_rounds }})
{% endblock %}

{% block content %}

    <h5 class="text-info text-center">Cash: {{ player.cash }};  Shares: {{ player.shares }}</h5>

    <p>
        If you want to buy shares, enter on the left the number of shares and the maximum buying price you desire.
        If you want to sell shares, enter on the right the number of shares and the minimum selling price you desire.
        The price you enter must be larger than 0. If you do not want to buy or sell shares, leave them empty and proceed.
        Please note that you may submit <strong>at most one order.</strong>
    </p>

    <!--
    TODO: Validate the form inputs:
    1. Only one order at a time
    2. Total(No of shares * price) should be less or equal to the cash position
    -->
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
          <div class="col-md-4">
            <h4>Order Type</h4>
            <!--load the form manually, to allow for addition of jquery functions-->
            <div class="form-group required">
                <label class="control-label" for="id_order_type"></label>
                <div class="controls  field-order_type">
                    <label class="radio-inline" for="id_order_type_1"><input id="id_order_type_1" value="Sell" name="order_type" required="" type="radio"> Sell</label>
                    <label class="radio-inline" for="id_order_type_2"><input id="id_order_type_2" value="Buy" name="order_type" required="" type="radio"> Buy</label>
                    <label class="radio-inline" for="id_order_type_3"><input id="id_order_type_3" value="None" name="order_type" required="" type="radio"> None</label>
                </div><!--- .controls -->
                </div>
          </div>
          <div style="display: none;" id="buyform">
              <div class="col-md-4">
                <h4>Buy Order</h4>
                {% formfield player.bn with label="Number of shares" %}
                {% formfield player.bp with label="for at most per share" %}
              </div>
          </div>
          <div style="display: none;"  id="sellform">
              <div class="col-md-4">
                <h4>Sell Order</h4>
                {% formfield player.sn with label="Number of shares" %}
                {% formfield player.sp with label="for at least per share" %}
              </div>
          </div>

        </div>
      </div>
    </div>

    <script>
        // script to show/ hide the order fields, based on order type
        $(document).ready(function(){
          $("#id_order_type_1").click(function(){
            $("#sellform").show();
            $("#buyform").hide();
          });
          $("#id_order_type_2").click(function(){
            $("#buyform").show();
            $("#sellform").hide();
          });
          $("#id_order_type_3").click(function(){
            $("#sellform").hide();
            $("#buyform").hide();
          });
        });
    </script>

    {% next_button %}

    {% include 'asset_market/Rules.html' %}

{% endblock %}

asset_market/templates/asset_market/Question.html
{% extends "global/Base.html" %}{% load staticfiles otree_tags %}{% block title %}    Understanding question ({{ num_q }} of {{ total_q }}){% endblock %}{% block content %}    <p>        To make sure that you have read the instruction carefully and understood it thoroughly,        please answer the following question. You will get feedback once you submit your answer.    </p>    {% if num_q == 1 %}    <p>        Participant 1 submits a buy order for 2 shares at maximum buying price of $3 per share. Participant 2 submits a sell order        for 3 shares at minimum selling price of $2 per share. What will the transaction price (P) and number of shares traded (N) be?    </p>        {% formfield player.understanding_question_1 with label="" %}    {% elif num_q == 2 %}    <p>        At the end of period 2, participant 1 has 4 shares and participant 2 has 6. The random draw determines that the dividend is $2        per share for period 2. How much dividends will participant 1 and 2 will receive respectively this period?    </p>        {% formfield player.understanding_question_2 with label="" %}    {% endif %}    {% next_button %}    {% include 'asset_market/Rules.html' %}{% endblock %}

asset_market/templates/asset_market/Results.html
{% extends "global/Base.html" %}{% load staticfiles otree_tags %}{% block title %}    Results{% endblock %}{% block content %}    <p>        You have finished all 5 periods. Your final positions are:        <h5 class="text-info text-center">Cash: {{ player.cash }};  Shares: {{ player.shares }}</h5>    </p>    <p>        The transactions and dividends for the 5 periods are summarized below:    </p>    <p>        {% include 'asset_market/ResultsChart.html' %}    </p>    <p>        Your shares are redeemed for free, so your payoff from the market is {{ player.cash }}.<br>        In addition, you received {{ player.participant.session.participation_fee }} for participation. Thus, your total payoff is {{ total_payoff }}.<br>    </p>    {% next_button %}{% endblock %}

asset_market/templates/asset_market/ResultsChart.html
<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

<script>

    $(function () {
    $('#container').highcharts({
        title: {
            text: '',
            x: -20 //center
        },
        xAxis: {
            categories: ['Period 1', 'Period 2', 'Period 3', 'Period 4', 'Period 5']
        },
        yAxis: {
            title: {
                text: ''
            },
            plotLines: [{
                value: 0,
                width: 1,
                color: '#808080'
            }]
        },
        legend: {
            layout: 'horizontal',
            verticalAlign: 'top',
            borderWidth: 0
        },
        series: [{
            name: 'Transaction Price',
            data: {{ transaction_price }}
        }, {
            name: 'Dividend/Share',
            data: {{ dividend_per_share }}
        }, {
            name: 'Shares Traded',
            data: {{ shares_traded }}
        }]
    });
});

</script>

asset_market/templates/asset_market/Rules.html
<div class="box effect7">

    <h4>Rules</h4>

    <h5>Buy/Sell Order:</h5>

    <p>
        At the beginning of each period, participants are free to submit buy/sell orders to trade shares. Participants submit orders
        simultaneously; neither sees the order from the other before submitting his/her own.
    </p>

    <p>
        To submit a buy order, participants should specify the maximum buying price per share (BP) and the number of shares (BN) they are
        willing to buy. To submit a sell order, participants should specify the minimum selling price per share (SP) and the number of
        shares (SN) they are willing to sell.
    </p>

    <p>
        Please note that you might only sell at most the number of shares you hold but not more; you might not buy more than you could
        afford with your cash. If you have no intention to buy or sell, you might stay put and submit no order at all. You might submit
        either buy/sell order but not both.
    </p>

    <h5>Market Clearing:</h5>

    <p>
        A transaction is only possible when one participant wants to buy and the other to sell. Moreover, the submitted maximum buying
        price (BP) has to be higher than the minimum selling price (SP). When this is the case, transaction takes place at the average
        of these two prices. That is transaction price (P) = 0.5*(BP+SP). The number of shares traded (N) equals the smaller of the two
        numbers, i.e. N is the minimum of BN and SN.
    </p>

    <p>
        If transaction takes place, N shares are removed from the selling party to the buying party; accordingly, cash equal to the
        transaction price (P) is added to the selling party and subtracted from the buying party.
    </p>

    <p>Otherwise, no transaction takes place and the orders submitted, if any, are not revealed to participants.</p>

    <h5>Dividends:</h5>
    <p>
        At the end of each period, dividends will be randomly drawn, with equal probabilities of being $1/share or $2/share. Dividend per
        share will be the same for all participants and all shares. Each participant is informed of the draw at the end of each period and
        distributed according to the shares he/she holds at the time.
    </p>
</div>

asset_market/templates/asset_market/Transaction.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Transaction (Period {{ round_num }} of {{ num_of_rounds }})
{% endblock %}

{% block content %}

    <p>
    {% if group.shares_traded %}
        You just {% if self.player.order_type == 'Buy' %} bought{% else %} sold {% endif %} {{ group.shares_traded }} shares at the price of {{ transaction_price }}.
        Now, your positions are the following:
    {% else %}
        No transaction took place this period. Your positions are not changed:
    {% endif %}
     </p>
    <h5 class="text-info text-center">Cash: {{ player.cash }};  Shares: {{ player.shares }}</h5>

    {% next_button %}

    {% include 'asset_market/Rules.html' %}

{% endblock %}